// ============================================================
// ACCOUNTANTS AFTER HOURS - DASHBOARD DATA
// Auto-generated by GitHub Actions on 2026-04-01
// YouTube & HubSpot are pulled LIVE via API.
// ============================================================

const DASHBOARD_DATA = {
  lastUpdated: "2026-04-01",
  reportingMonth: "March 2026",

  youtube: {
    subscribers: 31,
    subscriberGrowth: 31,
    totalViews: 3967,
    channelUrl: "https://www.youtube.com/@AccountantsAfterHours",
    episodes: [],
    monthlyViews: [
    {
        "month": "Feb 2026",
        "views": 4
    },
    {
        "month": "Mar 2026",
        "views": 28
    },
    {
        "month": "Apr 2026",
        "views": 0
    },
    {
        "month": "May 2026",
        "views": 0
    },
    {
        "month": "Jun 2026",
        "views": 0
    },
    {
        "month": "Jul 2026",
        "views": 0
    },
    {
        "month": "Aug 2026",
        "views": 0
    },
    {
        "month": "Sep 2026",
        "views": 0
    },
    {
        "month": "Oct 2026",
        "views": 0
    },
    {
        "month": "Nov 2026",
        "views": 0
    },
    {
        "month": "Dec 2026",
        "views": 0
    }
],
  },

  website: {
    visitors: 366,
    visitorGrowth: 366,
    topPages: [],
    monthlyVisitors: [
    {
        "month": "Feb 2026",
        "visitors": 0
    },
    {
        "month": "Mar 2026",
        "visitors": 366
    },
    {
        "month": "Apr 2026",
        "visitors": 0
    },
    {
        "month": "May 2026",
        "visitors": 0
    },
    {
        "month": "Jun 2026",
        "visitors": 0
    },
    {
        "month": "Jul 2026",
        "visitors": 0
    },
    {
        "month": "Aug 2026",
        "visitors": 0
    },
    {
        "month": "Sep 2026",
        "visitors": 0
    },
    {
        "month": "Oct 2026",
        "visitors": 0
    },
    {
        "month": "Nov 2026",
        "visitors": 0
    },
    {
        "month": "Dec 2026",
        "visitors": 0
    }
],
  },

  hubspot: {
    subscribers: 94,
    subscriberGrowth: 24,
    openRate: "0%",
    clickRate: "0%",
    monthlySubscribers: [
    {
        "month": "Feb 2026",
        "count": 70
    },
    {
        "month": "Mar 2026",
        "count": 86
    },
    {
        "month": "Apr 2026",
        "count": 0
    },
    {
        "month": "May 2026",
        "count": 0
    },
    {
        "month": "Jun 2026",
        "count": 0
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  podcast: {
    platform: "Acast",
    totalDownloads: 1163,
    monthlyDownloads: 1163,
    downloadGrowth: 1163,
    subscribers: 74,
    subscriberGrowth: 74,
    topEpisodes: [
    {
        "title": "Episode 1:  The 2025 Wrap, the 2026 Energy",
        "downloads": 733
    },
    {
        "title": "Episode 2: Will AI Take your Job?",
        "downloads": 279
    },
    {
        "title": "Episode 3: Bonus EP, AI already changed again",
        "downloads": 151
    }
],
    monthlyDownloads_history: [
    {
        "month": "Feb 2026",
        "downloads": 0
    },
    {
        "month": "Mar 2026",
        "downloads": 1163
    },
    {
        "month": "Apr 2026",
        "downloads": 0
    },
    {
        "month": "May 2026",
        "downloads": 0
    },
    {
        "month": "Jun 2026",
        "downloads": 0
    },
    {
        "month": "Jul 2026",
        "downloads": 0
    },
    {
        "month": "Aug 2026",
        "downloads": 0
    },
    {
        "month": "Sep 2026",
        "downloads": 0
    },
    {
        "month": "Oct 2026",
        "downloads": 0
    },
    {
        "month": "Nov 2026",
        "downloads": 0
    },
    {
        "month": "Dec 2026",
        "downloads": 0
    }
],
  },

  instagram: {
    followers: 267,
    followerGrowth: 267,
    postsThisMonth: 0,
    reach: 0,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.instagram.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 0
    },
    {
        "month": "Mar 2026",
        "count": 267
    },
    {
        "month": "Apr 2026",
        "count": 0
    },
    {
        "month": "May 2026",
        "count": 0
    },
    {
        "month": "Jun 2026",
        "count": 0
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  facebook: {
    followers: 53,
    followerGrowth: 11,
    reach: 0,
    engagement: "0%",
    profileUrl: "https://www.facebook.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 42
    },
    {
        "month": "Mar 2026",
        "count": 53
    },
    {
        "month": "Apr 2026",
        "count": 0
    },
    {
        "month": "May 2026",
        "count": 0
    },
    {
        "month": "Jun 2026",
        "count": 0
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  linkedin: {
    followers: 175,
    followerGrowth: 125,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.linkedin.com/company/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 50
    },
    {
        "month": "Mar 2026",
        "count": 175
    },
    {
        "month": "Apr 2026",
        "count": 0
    },
    {
        "month": "May 2026",
        "count": 0
    },
    {
        "month": "Jun 2026",
        "count": 0
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },
};
