// ============================================================
// ACCOUNTANTS AFTER HOURS - DASHBOARD DATA
// Auto-generated by GitHub Actions on 2026-10-02
// YouTube & HubSpot are pulled LIVE via API.
// ============================================================

const DASHBOARD_DATA = {
  lastUpdated: "2026-10-02",
  reportingMonth: "September 2026",

  youtube: {
    subscribers: 140,
    subscriberGrowth: 140,
    totalViews: 18479,
    channelUrl: "https://www.youtube.com/@AccountantsAfterHours",
    episodes: [
    {
        "title": "Accountants React to 2026 Federal Budget Tax Changes",
        "views": 276,
        "likes": 18,
        "publishedDate": "2026-05-18",
        "duration": 2967
    },
    {
        "title": "What We Fired, Cut, and Walked Away From",
        "views": 215,
        "likes": 4,
        "publishedDate": "2026-08-19",
        "duration": 3147
    },
    {
        "title": "State Of The Accounting Industry",
        "views": 175,
        "likes": 6,
        "publishedDate": "2026-07-15",
        "duration": 2909
    },
    {
        "title": "Mental Health in Accounting",
        "views": 152,
        "likes": 3,
        "publishedDate": "2026-06-15",
        "duration": 1985
    },
    {
        "title": "Holidays and Burnout + Industry update",
        "views": 142,
        "likes": 1,
        "publishedDate": "2026-08-12",
        "duration": 2396
    },
    {
        "title": "Live from Xerocon Denver with Angad Soin, Managing Director AU/NZ,Global Chief Strategy Officer Xero",
        "views": 129,
        "likes": 0,
        "publishedDate": "2026-09-23",
        "duration": 938
    },
    {
        "title": "Xerocon Denver Vlog Part 4: Xerocon Day Two and the Wrap Party",
        "views": 121,
        "likes": 2,
        "publishedDate": "2026-08-23",
        "duration": 719
    },
    {
        "title": "Best Accounting Firm Client Stories",
        "views": 121,
        "likes": 5,
        "publishedDate": "2026-07-01",
        "duration": 1717
    },
    {
        "title": "On the Road to Xerocon Denver 2026",
        "views": 115,
        "likes": 2,
        "publishedDate": "2026-07-29",
        "duration": 1936
    },
    {
        "title": "Xerocon Denver Vlog Part 3: Xerocon Day One",
        "views": 112,
        "likes": 3,
        "publishedDate": "2026-08-23",
        "duration": 644
    },
    {
        "title": "Xerocon Denver Vlog Part 1 : Sydney to LA to Denver: The Road to Xerocon 2026",
        "views": 106,
        "likes": 3,
        "publishedDate": "2026-08-16",
        "duration": 611
    },
    {
        "title": "Live from Xerocon Denver with Matthew May : The Tech CPA",
        "views": 104,
        "likes": 2,
        "publishedDate": "2026-08-26",
        "duration": 1579
    },
    {
        "title": "Growing your accounting firm in 2026",
        "views": 97,
        "likes": 3,
        "publishedDate": "2026-06-03",
        "duration": 1647
    },
    {
        "title": "Live from Xerocon Denver with Isaac Perdomo, AI Automation Partner for $1-$10M Accounting Firms",
        "views": 91,
        "likes": 0,
        "publishedDate": "2026-09-08",
        "duration": 1253
    }
],
    shorts: [
    {
        "title": "New service offering?",
        "views": 1479,
        "likes": 5,
        "publishedDate": "2026-05-18",
        "duration": 24
    },
    {
        "title": "This is who we're interviewing at Xerocon Denver 2026",
        "views": 1255,
        "likes": 0,
        "publishedDate": "2026-08-02",
        "duration": 21
    },
    {
        "title": "How the proposed CGT change could make Australia uncompetitive (2026 Federal Budget breakdown)",
        "views": 1092,
        "likes": 22,
        "publishedDate": "2026-06-03",
        "duration": 103
    },
    {
        "title": "What Australia's proposed increase to trust tax means for 240,000 small businesses",
        "views": 991,
        "likes": 20,
        "publishedDate": "2026-06-07",
        "duration": 101
    },
    {
        "title": "What to do when a client leaves mid-year and asks for their money back",
        "views": 849,
        "likes": 4,
        "publishedDate": "2026-05-24",
        "duration": 49
    },
    {
        "title": "The cheapest insurance might be a second opinion",
        "views": 599,
        "likes": 0,
        "publishedDate": "2026-07-26",
        "duration": 15
    },
    {
        "title": "Selling your business in Australia could cost a lot more after 2027 (2026 Federal Budget impact)",
        "views": 515,
        "likes": 8,
        "publishedDate": "2026-06-06",
        "duration": 77
    },
    {
        "title": "You can\u2019t tell the ATO ...",
        "views": 401,
        "likes": 2,
        "publishedDate": "2026-09-17",
        "duration": 38
    },
    {
        "title": "The KPMG inquiry and the push to break up the Big 4",
        "views": 268,
        "likes": 2,
        "publishedDate": "2026-08-16",
        "duration": 100
    },
    {
        "title": "How to survive Xerocon Denver 2026",
        "views": 268,
        "likes": 1,
        "publishedDate": "2026-08-10",
        "duration": 33
    },
    {
        "title": "Are Australian accounting firms actually ahead of the US when it comes to tech and AI?",
        "views": 265,
        "likes": 2,
        "publishedDate": "2026-09-27",
        "duration": 56
    },
    {
        "title": "What working from home really does to your ability to switch off",
        "views": 234,
        "likes": 1,
        "publishedDate": "2026-06-23",
        "duration": 142
    },
    {
        "title": "Why \"hold\" is the most common word in client meetings right now",
        "views": 220,
        "likes": 0,
        "publishedDate": "2026-07-19",
        "duration": 93
    },
    {
        "title": "Not every accounting workflow needs an AI agent \ud83d\udc40",
        "views": 183,
        "likes": 1,
        "publishedDate": "2026-09-15",
        "duration": 44
    },
    {
        "title": "The messaging audit every accounting firm needs to run",
        "views": 182,
        "likes": 0,
        "publishedDate": "2026-06-14",
        "duration": 88
    },
    {
        "title": "Who are you actually building your business for?",
        "views": 150,
        "likes": 0,
        "publishedDate": "2026-06-28",
        "duration": 84
    },
    {
        "title": "Everyone wants to jump straight to the exciting part: automation \ud83e\udd16",
        "views": 146,
        "likes": 0,
        "publishedDate": "2026-09-15",
        "duration": 37
    },
    {
        "title": "Xerocon Denver Vlog Part 2: Early Flights, Margaritas and the Pre-Con Party",
        "views": 139,
        "likes": 4,
        "publishedDate": "2026-08-22",
        "duration": 387
    },
    {
        "title": "Should business owners take their laptop on holiday?",
        "views": 131,
        "likes": 0,
        "publishedDate": "2026-08-12",
        "duration": 90
    },
    {
        "title": "The tradie who nearly shut his business down (and what changed)",
        "views": 106,
        "likes": 1,
        "publishedDate": "2026-07-01",
        "duration": 103
    },
    {
        "title": "Stop relying on referrals to grow your accounting firm",
        "views": 105,
        "likes": 0,
        "publishedDate": "2026-06-03",
        "duration": 82
    },
    {
        "title": "How to land accounting clients from ChatGPT",
        "views": 92,
        "likes": 0,
        "publishedDate": "2026-06-10",
        "duration": 115
    },
    {
        "title": "The best person to lead AI",
        "views": 84,
        "likes": 0,
        "publishedDate": "2026-09-25",
        "duration": 49
    },
    {
        "title": "Working harder vs working smarter in your accounting firm",
        "views": 68,
        "likes": 0,
        "publishedDate": "2026-08-29",
        "duration": 126
    },
    {
        "title": "Why your accounting inbox will never be empty (and why that's fine)",
        "views": 67,
        "likes": 3,
        "publishedDate": "2026-06-17",
        "duration": 106
    },
    {
        "title": "We\u2019re roving reporters at Xerocon Denver 2026",
        "views": 64,
        "likes": 0,
        "publishedDate": "2026-07-29",
        "duration": 117
    },
    {
        "title": "Live from Xerocon Denver with Della Hudson",
        "views": 54,
        "likes": 0,
        "publishedDate": "2026-09-09",
        "duration": 382
    },
    {
        "title": "Client red flags accountants watch for",
        "views": 38,
        "likes": 0,
        "publishedDate": "2026-09-01",
        "duration": 102
    },
    {
        "title": "Why Australian business owners are considering moving offshore in 2026",
        "views": 27,
        "likes": 0,
        "publishedDate": "2026-07-15",
        "duration": 136
    },
    {
        "title": "Should accounting clients have your mobile number?",
        "views": 22,
        "likes": 0,
        "publishedDate": "2026-08-19",
        "duration": 117
    },
    {
        "title": "What a business owner really needs when finances fall apart",
        "views": 21,
        "likes": 0,
        "publishedDate": "2026-07-07",
        "duration": 94
    },
    {
        "title": "The $20K phone call that left a client speechless",
        "views": 20,
        "likes": 0,
        "publishedDate": "2026-07-13",
        "duration": 85
    },
    {
        "title": "Blockbuster vs Netflix AI",
        "views": 19,
        "likes": 0,
        "publishedDate": "2026-09-08",
        "duration": 124
    },
    {
        "title": "The accounting firm of 2030",
        "views": 19,
        "likes": 0,
        "publishedDate": "2026-09-08",
        "duration": 88
    },
    {
        "title": "Are AI-native accounting firms actually winning?",
        "views": 16,
        "likes": 0,
        "publishedDate": "2026-08-24",
        "duration": 93
    },
    {
        "title": "Before you paste client data into an AI tool",
        "views": 4,
        "likes": 0,
        "publishedDate": "2026-09-29",
        "duration": 53
    }
],
    monthlyViews: [
    {
        "month": "Feb 2026",
        "views": 4
    },
    {
        "month": "Mar 2026",
        "views": 32
    },
    {
        "month": "Apr 2026",
        "views": 44
    },
    {
        "month": "May 2026",
        "views": 81
    },
    {
        "month": "Jun 2026",
        "views": 99
    },
    {
        "month": "Jul 2026",
        "views": 114
    },
    {
        "month": "Aug 2026",
        "views": 0
    },
    {
        "month": "Sep 2026",
        "views": 0
    },
    {
        "month": "Oct 2026",
        "views": 0
    },
    {
        "month": "Nov 2026",
        "views": 0
    },
    {
        "month": "Dec 2026",
        "views": 0
    }
],
  },

  website: {
    visitors: 0,
    visitorGrowth: 0,
    topPages: [],
    monthlyVisitors: [
    {
        "month": "Feb 2026",
        "visitors": 0
    },
    {
        "month": "Mar 2026",
        "visitors": 366
    },
    {
        "month": "Apr 2026",
        "visitors": 156
    },
    {
        "month": "May 2026",
        "visitors": 198
    },
    {
        "month": "Jun 2026",
        "visitors": 93
    },
    {
        "month": "Jul 2026",
        "visitors": 92
    },
    {
        "month": "Aug 2026",
        "visitors": 0
    },
    {
        "month": "Sep 2026",
        "visitors": 0
    },
    {
        "month": "Oct 2026",
        "visitors": 0
    },
    {
        "month": "Nov 2026",
        "visitors": 0
    },
    {
        "month": "Dec 2026",
        "visitors": 0
    }
],
  },

  hubspot: {
    subscribers: 101,
    subscriberGrowth: 101,
    openRate: "0%",
    clickRate: "0%",
    monthlySubscribers: [
    {
        "month": "Feb 2026",
        "count": 70
    },
    {
        "month": "Mar 2026",
        "count": 94
    },
    {
        "month": "Apr 2026",
        "count": 94
    },
    {
        "month": "May 2026",
        "count": 99
    },
    {
        "month": "Jun 2026",
        "count": 100
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  podcast: {
    platform: "Acast",
    totalDownloads: 4307,
    monthlyDownloads: 0,
    downloadGrowth: 0,
    subscribers: 0,
    subscriberGrowth: 0,
    topEpisodes: [
    {
        "title": "1: The 2025 Wrap, the 2026 Energy",
        "downloads": 894
    },
    {
        "title": "8: Accountants React to the 2026 Federal Budget",
        "downloads": 438
    },
    {
        "title": "2: Will AI Take your Job?",
        "downloads": 430
    },
    {
        "title": "5: Accountants v Bookkeepers",
        "downloads": 405
    },
    {
        "title": "6: Tax Planning Made Simple",
        "downloads": 350
    },
    {
        "title": "3: Bonus EP, AI already changed again",
        "downloads": 328
    },
    {
        "title": "7: Show me the money reengagemens",
        "downloads": 328
    },
    {
        "title": "9: Growing your firm in 2026",
        "downloads": 306
    },
    {
        "title": "4: Live from the Accounting & Business Expo",
        "downloads": 282
    },
    {
        "title": "10: Mental Health in Accounting",
        "downloads": 282
    }
],
    monthlyDownloads_history: [
    {
        "month": "Feb 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Mar 2026",
        "downloads": 1163,
        "subscribers": 0
    },
    {
        "month": "Apr 2026",
        "downloads": 775,
        "subscribers": 0
    },
    {
        "month": "May 2026",
        "downloads": 915,
        "subscribers": 0
    },
    {
        "month": "Jun 2026",
        "downloads": 832,
        "subscribers": 0
    },
    {
        "month": "Jul 2026",
        "downloads": 622,
        "subscribers": 0
    },
    {
        "month": "Aug 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Sep 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Oct 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Nov 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Dec 2026",
        "downloads": 0,
        "subscribers": 0
    }
],
  },

  instagram: {
    followers: 0,
    followerGrowth: 0,
    postsThisMonth: 0,
    reach: 0,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.instagram.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 0
    },
    {
        "month": "Mar 2026",
        "count": 267
    },
    {
        "month": "Apr 2026",
        "count": 515
    },
    {
        "month": "May 2026",
        "count": 750
    },
    {
        "month": "Jun 2026",
        "count": 1221
    },
    {
        "month": "Jul 2026",
        "count": 1611
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  facebook: {
    followers: 0,
    followerGrowth: 0,
    reach: 0,
    engagement: "0%",
    profileUrl: "https://www.facebook.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 42
    },
    {
        "month": "Mar 2026",
        "count": 53
    },
    {
        "month": "Apr 2026",
        "count": 56
    },
    {
        "month": "May 2026",
        "count": 65
    },
    {
        "month": "Jun 2026",
        "count": 80
    },
    {
        "month": "Jul 2026",
        "count": 85
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  linkedin: {
    followers: 0,
    followerGrowth: 0,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.linkedin.com/company/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 50
    },
    {
        "month": "Mar 2026",
        "count": 175
    },
    {
        "month": "Apr 2026",
        "count": 186
    },
    {
        "month": "May 2026",
        "count": 190
    },
    {
        "month": "Jun 2026",
        "count": 202
    },
    {
        "month": "Jul 2026",
        "count": 212
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },
};
