// ============================================================
// ACCOUNTANTS AFTER HOURS - DASHBOARD DATA
// Auto-generated by GitHub Actions on 2026-07-02
// YouTube & HubSpot are pulled LIVE via API.
// ============================================================

const DASHBOARD_DATA = {
  lastUpdated: "2026-07-02",
  reportingMonth: "June 2026",

  youtube: {
    subscribers: 100,
    subscriberGrowth: 100,
    totalViews: 12319,
    channelUrl: "https://www.youtube.com/@AccountantsAfterHours",
    episodes: [
    {
        "title": "Accountants React to 2026 Federal Budget Tax Changes",
        "views": 258,
        "likes": 18,
        "publishedDate": "2026-05-18",
        "duration": 2967
    },
    {
        "title": "Accountants vs Bookkeepers",
        "views": 168,
        "likes": 5,
        "publishedDate": "2026-04-15",
        "duration": 1672
    },
    {
        "title": "Tax Planning Made Simple",
        "views": 148,
        "likes": 3,
        "publishedDate": "2026-04-29",
        "duration": 1780
    },
    {
        "title": "Mental Health in Accounting",
        "views": 124,
        "likes": 1,
        "publishedDate": "2026-06-15",
        "duration": 1984
    },
    {
        "title": "Bonus Ep AI Already Changed\u2026 Again",
        "views": 109,
        "likes": 7,
        "publishedDate": "2026-03-23",
        "duration": 1313
    },
    {
        "title": "Show Me the Money: Re-Engagements",
        "views": 102,
        "likes": 4,
        "publishedDate": "2026-05-06",
        "duration": 2806
    },
    {
        "title": "The 2025 Wrap, the 2026 Energy",
        "views": 99,
        "likes": 7,
        "publishedDate": "2026-02-25",
        "duration": 2566
    },
    {
        "title": "Growing your accounting firm in 2026",
        "views": 85,
        "likes": 3,
        "publishedDate": "2026-06-03",
        "duration": 1647
    },
    {
        "title": "Will AI Take Your Job?",
        "views": 78,
        "likes": 4,
        "publishedDate": "2026-03-10",
        "duration": 2919
    },
    {
        "title": "Best Accounting Firm Client Stories",
        "views": 2,
        "likes": 1,
        "publishedDate": "2026-07-01",
        "duration": 1717
    }
],
    shorts: [
    {
        "title": "Are you missing the industry events that matter?",
        "views": 1572,
        "likes": 6,
        "publishedDate": "2026-03-05",
        "duration": 36
    },
    {
        "title": "New service offering?",
        "views": 1479,
        "likes": 5,
        "publishedDate": "2026-05-18",
        "duration": 24
    },
    {
        "title": "Would you let a client go for using AI?",
        "views": 1159,
        "likes": 1,
        "publishedDate": "2026-03-25",
        "duration": 43
    },
    {
        "title": "How the proposed CGT change could make Australia uncompetitive (2026 Federal Budget breakdown)",
        "views": 1051,
        "likes": 19,
        "publishedDate": "2026-06-03",
        "duration": 103
    },
    {
        "title": "The receipt rule bookkeepers keep getting wrong\u2026",
        "views": 1045,
        "likes": 4,
        "publishedDate": "2026-04-27",
        "duration": 94
    },
    {
        "title": "What Australia's proposed increase to trust tax means for 240,000 small businesses",
        "views": 990,
        "likes": 20,
        "publishedDate": "2026-06-07",
        "duration": 101
    },
    {
        "title": "What to do when a client leaves mid-year and asks for their money back",
        "views": 847,
        "likes": 4,
        "publishedDate": "2026-05-24",
        "duration": 49
    },
    {
        "title": "Selling your business in Australia could cost a lot more after 2027 (2026 Federal Budget impact)",
        "views": 506,
        "likes": 8,
        "publishedDate": "2026-06-06",
        "duration": 77
    },
    {
        "title": "Not LinkedIn safe",
        "views": 271,
        "likes": 2,
        "publishedDate": "2026-02-10",
        "duration": 27
    },
    {
        "title": "The cowboy accountant that got caught \ud83d\udc40",
        "views": 235,
        "likes": 0,
        "publishedDate": "2026-03-12",
        "duration": 55
    },
    {
        "title": "What working from home really does to your ability to switch off",
        "views": 234,
        "likes": 1,
        "publishedDate": "2026-06-23",
        "duration": 142
    },
    {
        "title": "Behind the Scenes Snippets - Sneak Peak",
        "views": 176,
        "likes": 8,
        "publishedDate": "2026-02-08",
        "duration": 166
    },
    {
        "title": "The messaging audit every accounting firm needs to run",
        "views": 175,
        "likes": 0,
        "publishedDate": "2026-06-14",
        "duration": 88
    },
    {
        "title": "The admin job AI killed forever",
        "views": 155,
        "likes": 2,
        "publishedDate": "2026-03-29",
        "duration": 67
    },
    {
        "title": "Who are you actually building your business for?",
        "views": 150,
        "likes": 0,
        "publishedDate": "2026-06-28",
        "duration": 84
    },
    {
        "title": "Why accounting firms lose staff every June (and how to stop it)",
        "views": 135,
        "likes": 0,
        "publishedDate": "2026-05-10",
        "duration": 59
    },
    {
        "title": "Why accountants who only do compliance are falling behind (and what to do instead)",
        "views": 118,
        "likes": 1,
        "publishedDate": "2026-04-29",
        "duration": 60
    },
    {
        "title": "Are accountants becoming redundant in 2026?",
        "views": 109,
        "likes": 1,
        "publishedDate": "2026-03-09",
        "duration": 45
    },
    {
        "title": "Stop relying on referrals to grow your accounting firm",
        "views": 105,
        "likes": 0,
        "publishedDate": "2026-06-03",
        "duration": 82
    },
    {
        "title": "Are women in accounting seen as unapproachable?",
        "views": 103,
        "likes": 1,
        "publishedDate": "2026-03-02",
        "duration": 39
    },
    {
        "title": "Has anyone fully automated AP yet?",
        "views": 95,
        "likes": 0,
        "publishedDate": "2026-03-31",
        "duration": 33
    },
    {
        "title": "How to land accounting clients from ChatGPT",
        "views": 90,
        "likes": 0,
        "publishedDate": "2026-06-10",
        "duration": 115
    },
    {
        "title": "Not your typical accounting podcast. Definitely not LinkedIn safe.",
        "views": 78,
        "likes": 2,
        "publishedDate": "2026-03-08",
        "duration": 14
    },
    {
        "title": "The tradie who nearly shut his business down (and what changed)",
        "views": 69,
        "likes": 0,
        "publishedDate": "2026-07-01",
        "duration": 103
    },
    {
        "title": "Why your accounting inbox will never be empty (and why that's fine)",
        "views": 59,
        "likes": 3,
        "publishedDate": "2026-06-17",
        "duration": 106
    },
    {
        "title": "The highest-value service you're probably undercharging for",
        "views": 56,
        "likes": 0,
        "publishedDate": "2026-05-06",
        "duration": 96
    },
    {
        "title": "Should accountants build their own AI or wait for the software?",
        "views": 50,
        "likes": 0,
        "publishedDate": "2026-03-24",
        "duration": 47
    },
    {
        "title": "Why accounting firms should stop invoicing as they go",
        "views": 34,
        "likes": 0,
        "publishedDate": "2026-05-06",
        "duration": 112
    },
    {
        "title": "This is what accountants need to know about AI Agents in 2026",
        "views": 31,
        "likes": 1,
        "publishedDate": "2026-03-18",
        "duration": 69
    },
    {
        "title": "Bloopers",
        "views": 28,
        "likes": 1,
        "publishedDate": "2026-05-11",
        "duration": 23
    },
    {
        "title": "Why don\u2019t accountants and bookkeepers get along?",
        "views": 24,
        "likes": 0,
        "publishedDate": "2026-04-15",
        "duration": 70
    },
    {
        "title": "Why accountants and bookkeepers are debating the way BAS\u2019s are entered into the accounting system",
        "views": 20,
        "likes": 1,
        "publishedDate": "2026-04-19",
        "duration": 78
    }
],
    monthlyViews: [
    {
        "month": "Feb 2026",
        "views": 4
    },
    {
        "month": "Mar 2026",
        "views": 32
    },
    {
        "month": "Apr 2026",
        "views": 44
    },
    {
        "month": "May 2026",
        "views": 81
    },
    {
        "month": "Jun 2026",
        "views": 99
    },
    {
        "month": "Jul 2026",
        "views": 0
    },
    {
        "month": "Aug 2026",
        "views": 0
    },
    {
        "month": "Sep 2026",
        "views": 0
    },
    {
        "month": "Oct 2026",
        "views": 0
    },
    {
        "month": "Nov 2026",
        "views": 0
    },
    {
        "month": "Dec 2026",
        "views": 0
    }
],
  },

  website: {
    visitors: 93,
    visitorGrowth: -105,
    topPages: [],
    monthlyVisitors: [
    {
        "month": "Feb 2026",
        "visitors": 0
    },
    {
        "month": "Mar 2026",
        "visitors": 366
    },
    {
        "month": "Apr 2026",
        "visitors": 156
    },
    {
        "month": "May 2026",
        "visitors": 198
    },
    {
        "month": "Jun 2026",
        "visitors": 93
    },
    {
        "month": "Jul 2026",
        "visitors": 0
    },
    {
        "month": "Aug 2026",
        "visitors": 0
    },
    {
        "month": "Sep 2026",
        "visitors": 0
    },
    {
        "month": "Oct 2026",
        "visitors": 0
    },
    {
        "month": "Nov 2026",
        "visitors": 0
    },
    {
        "month": "Dec 2026",
        "visitors": 0
    }
],
  },

  hubspot: {
    subscribers: 100,
    subscriberGrowth: 1,
    openRate: "0%",
    clickRate: "0%",
    monthlySubscribers: [
    {
        "month": "Feb 2026",
        "count": 70
    },
    {
        "month": "Mar 2026",
        "count": 94
    },
    {
        "month": "Apr 2026",
        "count": 94
    },
    {
        "month": "May 2026",
        "count": 99
    },
    {
        "month": "Jun 2026",
        "count": 100
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  podcast: {
    platform: "Acast",
    totalDownloads: 3685,
    monthlyDownloads: 832,
    downloadGrowth: -83,
    subscribers: 0,
    subscriberGrowth: 0,
    topEpisodes: [
    {
        "title": "1: The 2025 Wrap, the 2026 Energy",
        "downloads": 875
    },
    {
        "title": "2: Will AI Take your Job?",
        "downloads": 412
    },
    {
        "title": "8: Accountants React to the 2026 Federal Budget",
        "downloads": 412
    },
    {
        "title": "5: Accountants v Bookkeepers",
        "downloads": 370
    },
    {
        "title": "6: Tax Planning Made Simple",
        "downloads": 314
    },
    {
        "title": "3: Bonus EP, AI already changed again",
        "downloads": 313
    },
    {
        "title": "7: Show me the money reengagemens",
        "downloads": 292
    },
    {
        "title": "4: Live from the Accounting & Business Expo",
        "downloads": 271
    },
    {
        "title": "9: Growing your firm in 2026",
        "downloads": 245
    },
    {
        "title": "10: Mental Health in Accounting",
        "downloads": 181
    }
],
    monthlyDownloads_history: [
    {
        "month": "Feb 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Mar 2026",
        "downloads": 1163,
        "subscribers": 0
    },
    {
        "month": "Apr 2026",
        "downloads": 775,
        "subscribers": 0
    },
    {
        "month": "May 2026",
        "downloads": 915,
        "subscribers": 0
    },
    {
        "month": "Jun 2026",
        "downloads": 832,
        "subscribers": 0
    },
    {
        "month": "Jul 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Aug 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Sep 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Oct 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Nov 2026",
        "downloads": 0,
        "subscribers": 0
    },
    {
        "month": "Dec 2026",
        "downloads": 0,
        "subscribers": 0
    }
],
  },

  instagram: {
    followers: 1221,
    followerGrowth: 471,
    postsThisMonth: 0,
    reach: 0,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.instagram.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 0
    },
    {
        "month": "Mar 2026",
        "count": 267
    },
    {
        "month": "Apr 2026",
        "count": 515
    },
    {
        "month": "May 2026",
        "count": 750
    },
    {
        "month": "Jun 2026",
        "count": 1221
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  facebook: {
    followers: 80,
    followerGrowth: 15,
    reach: 0,
    engagement: "0%",
    profileUrl: "https://www.facebook.com/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 42
    },
    {
        "month": "Mar 2026",
        "count": 53
    },
    {
        "month": "Apr 2026",
        "count": 56
    },
    {
        "month": "May 2026",
        "count": 65
    },
    {
        "month": "Jun 2026",
        "count": 80
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },

  linkedin: {
    followers: 202,
    followerGrowth: 12,
    impressions: 0,
    engagement: "0%",
    profileUrl: "https://www.linkedin.com/company/accountantsafterhours",
    monthlyFollowers: [
    {
        "month": "Feb 2026",
        "count": 50
    },
    {
        "month": "Mar 2026",
        "count": 175
    },
    {
        "month": "Apr 2026",
        "count": 186
    },
    {
        "month": "May 2026",
        "count": 190
    },
    {
        "month": "Jun 2026",
        "count": 202
    },
    {
        "month": "Jul 2026",
        "count": 0
    },
    {
        "month": "Aug 2026",
        "count": 0
    },
    {
        "month": "Sep 2026",
        "count": 0
    },
    {
        "month": "Oct 2026",
        "count": 0
    },
    {
        "month": "Nov 2026",
        "count": 0
    },
    {
        "month": "Dec 2026",
        "count": 0
    }
],
  },
};
